---
- name: Criação de Usuário
  hosts: all
  remote_user: root
  vars:
    senha: senha
    usuario: fulano
  tasks:
    - name: Instação do pacote whois
      ansible.builtin.apt:
        name: whois
        state: present
        update_cache: true
    - name: Gerar senha criptografada
      ansible.builtin.shell: "mkpasswd --method=sha-512 {{ senha }}"
      register: cripto_pwd
    - name: Criar o usuário no Linux
      ansible.builtin.user:
        name: "{{ usuario }}"
        shell: /bin/bash
        groups: sudo
        append: yes
        password: "{{ cripto_pwd.stdout}}"
    - name: Criar o diretório .ssh
      ansible.builtin.file:
        path: "/home/{{ usuario }}/.ssh"
        state: directory
        group: "{{ usuario }}"
        owner: "{{ usuario }}"
        recurse: true
    - name: Copiando a chave .ssh
      ansible.builtin.copy:
        src: ~/Documents/digitalocean/terraform.pub
        dest: "/home/{{ usuario }}/.ssh/authorized_keys"